package neo4j.relations;

public interface Relations {

  String ENTITY_LOG = "ENTITY_LOG";

  String COMMENTABLE_COMMENT = "COMMENTABLE_COMMENT";

  String MODEL_AUTHOR = "MODEL_AUTHOR";

  String REQUIREMENT_REQUIREMENT = "REQUIREMENT_REQUIREMENT";

  String PROJECT_REQUIREMENT = "PROJECT_REQUIREMENT";
}
